language: python

python:
  - "3.6"

os:
  - linux

sudo: required

services:
  - docker

before_install:
  - docker pull busybox
  - docker pull alpine

install:
  - python setup.py install

script:
  - pip install coverage pytest-cov codecov
  - python setup.py test

after_success:
  - codecov


