version: '3.5'

services:
  shepherd:
    image: oldwebtoday/shepherd:1.1.0
    build: ./

    depends_on:
    - redis

    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./shepherd/static_base/:/app/shepherd/static_base/
    - ./shepherd/templates/:/app/shepherd/templates/

    environment:
    - DEBUG=1
    - WEBRTC_STUN_SERVER=stun:h2.nfbonf.nfb.ca
    - WEBRTC_TURN_REALM=h2.nfbonf.nfb.ca
    - WEBRTC_TURN_REST_AUTH_SECRET=TURNSECRET

    ports:
    - 9020:9020

  coturn:
    image: oldwebtoday/coturn:4.5.1.1
    build: ./coturn/
    command: bash -x /tmp/run.sh

    ports:
    - 33478:33478
    - 33479:33479

  redis:
    image: redis:3.2.4



