version: '3.5'

services:
    shepherd:
        image: oldwebtoday/shepherd:1.1.0-dev
        build: ./
        
        depends_on:
            - redis

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

        ports:
            - 9020:9020


    redis:
        image: redis:3.2.4


